# Generated by Django 5.0.6 on 2024-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('employer', models.PositiveBigIntegerField(verbose_name='Зарплата')),
                ('url', models.URLField(verbose_name='Ссылка на вакансию')),
            ],
        ),
    ]
