# Generated by Django 5.0.6 on 2024-07-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='employer',
            new_name='salary',
        ),
    ]
